### ISSUE TITLE
Application WebView is not working

### ISSUE THREAD

**Issue by umairlodhi** [mgks/Android-SmartWebView#80] opened 2019-03-16 06:05 UTC
**Describe the bug**
hi i am trying to create a webView application by using your code but when i run the project it closes automatically after the splash screen. i have changed the url and removed some permissions.

i have changed url in SmartWebView.java on line number 65
//complete URL of your website or offline webpage
	static String ASWV_URL          = "https://sitename.com/";
and commented permission in AndroidManifest.xml from line number 29 to 32 & 36 to 37..

Please guide me 
Thanks

**Comment by mgks** [comment] 2019-03-16 13:14
you also have to disable the variables from SmartWebView.java that directly or indirectly affect the permissions you commented out.

That's the only justifiable reason in this condition.

**Comment by kould** [comment] 2019-03-21 03:25
I have a similar problem, I can not run the app the error that I get is the following:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mgks.os.webview, PID: 4027
    java.lang.RuntimeException: Unable to start activity ComponentInfo{mgks.os.webview/mgks.os.webview.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewTreeObserver android.webkit.WebView.getViewTreeObserver()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6942)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewTreeObserver android.webkit.WebView.getViewTreeObserver()' on a null object reference
        at mgks.os.webview.MainActivity.onCreate(MainActivity.java:184)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1221)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6942) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
Application terminated.

Help me Please

**Comment by mgks** [comment] 2019-03-25 11:36
@kould I apologize for not noticing if any earlier, it's fixed now. just update your repo.

**Comment by kould** [comment] 2020-07-31 15:39
Hi how are you? We continue to use your project and it is impressive, very good, the only thing I need is to ask you for some help, I cannot use the links to share, for example whatsapp: // send me the error of Err_unknown_url_scheme I am a little newbie in the topic of android studio I would appreciate some help

**Comment by mgks** [comment] 2020-08-09 06:30
Use this scheme: https://faq.whatsapp.com/iphone/how-to-link-to-whatsapp-from-a-different-app
Will work.

**Closed by mgks** 2020-08-09 06:30 UTC
Labels: help, personal
